// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'narrative-citation-label'
  | 'narrative-citation-unavailable-flagged'
  | 'narrative-citation-unavailable-generic'
  | 'narrative-citation-unavailable-multi'
  | 'narrative-citation-unavailable-nodate'
  | 'narrative-citation-unavailable-note'
  | 'narrative-citation-unavailable-numeric';
